/********************************************************************************
** Form generated from reading UI file 'dialogcommandset.ui'
**
** Created by: Qt User Interface Compiler version 5.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOGCOMMANDSET_H
#define UI_DIALOGCOMMANDSET_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFormLayout>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include <qcustombutton.h>
#include <qcustomgroupbox.h>

QT_BEGIN_NAMESPACE

class Ui_DialogCommandSet
{
public:
    QGridLayout *gridLayout;
    QCustomGroupBox *groupBox_control_setting;
    QLabel *label_command_3;
    QCustomButton *toolButton_set_command_2;
    QPlainTextEdit *plainTextEdit_command_tx_2;
    QLabel *label_command_20;
    QPlainTextEdit *plainTextEdit_command_rx_2;
    QWidget *layoutWidget_3;
    QFormLayout *formLayout_12;
    QLabel *label_command_21;
    QPlainTextEdit *plainTextEdit_range_8;
    QLabel *label_command_22;
    QPlainTextEdit *plainTextEdit_range_9;
    QLabel *label_command_23;
    QPlainTextEdit *plainTextEdit_range_10;
    QLabel *label_command_24;
    QPlainTextEdit *plainTextEdit_range_11;
    QLabel *label_command_25;
    QPlainTextEdit *plainTextEdit_range_12;
    QLabel *label_command_26;
    QPlainTextEdit *plainTextEdit_range_13;
    QLabel *label_command_27;
    QPlainTextEdit *plainTextEdit_range_14;
    QLabel *label_command_28;
    QPlainTextEdit *plainTextEdit_range_15;
    QWidget *layoutWidget_4;
    QFormLayout *formLayout_13;
    QLabel *label_command_29;
    QPlainTextEdit *plainTextEdit_freq_7;
    QLabel *label_command_30;
    QLabel *label_command_31;
    QLabel *label_command_32;
    QLabel *label_command_33;
    QLabel *label_command_34;
    QPlainTextEdit *plainTextEdit_freq_8;
    QPlainTextEdit *plainTextEdit_freq_9;
    QPlainTextEdit *plainTextEdit_freq_10;
    QPlainTextEdit *plainTextEdit_freq_11;
    QPlainTextEdit *plainTextEdit_freq_12;
    QPushButton *pushButton_save;
    QPushButton *pushButton_2;

    void setupUi(QDialog *DialogCommandSet)
    {
        if (DialogCommandSet->objectName().isEmpty())
            DialogCommandSet->setObjectName(QStringLiteral("DialogCommandSet"));
        DialogCommandSet->resize(903, 838);
        gridLayout = new QGridLayout(DialogCommandSet);
        gridLayout->setObjectName(QStringLiteral("gridLayout"));
        groupBox_control_setting = new QCustomGroupBox(DialogCommandSet);
        groupBox_control_setting->setObjectName(QStringLiteral("groupBox_control_setting"));
        label_command_3 = new QLabel(groupBox_control_setting);
        label_command_3->setObjectName(QStringLiteral("label_command_3"));
        label_command_3->setGeometry(QRect(10, 20, 161, 31));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(label_command_3->sizePolicy().hasHeightForWidth());
        label_command_3->setSizePolicy(sizePolicy);
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(16, 32, 64, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(0, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        QBrush brush3(QColor(255, 255, 220, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_3->setPalette(palette);
        QFont font;
        font.setPointSize(16);
        label_command_3->setFont(font);
        label_command_3->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_3->setAlignment(Qt::AlignCenter);
        toolButton_set_command_2 = new QCustomButton(groupBox_control_setting);
        toolButton_set_command_2->setObjectName(QStringLiteral("toolButton_set_command_2"));
        toolButton_set_command_2->setGeometry(QRect(610, 570, 171, 41));
        plainTextEdit_command_tx_2 = new QPlainTextEdit(groupBox_control_setting);
        plainTextEdit_command_tx_2->setObjectName(QStringLiteral("plainTextEdit_command_tx_2"));
        plainTextEdit_command_tx_2->setGeometry(QRect(210, 10, 671, 71));
        label_command_20 = new QLabel(groupBox_control_setting);
        label_command_20->setObjectName(QStringLiteral("label_command_20"));
        label_command_20->setGeometry(QRect(10, 100, 161, 31));
        sizePolicy.setHeightForWidth(label_command_20->sizePolicy().hasHeightForWidth());
        label_command_20->setSizePolicy(sizePolicy);
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_20->setPalette(palette1);
        label_command_20->setFont(font);
        label_command_20->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_20->setAlignment(Qt::AlignCenter);
        plainTextEdit_command_rx_2 = new QPlainTextEdit(groupBox_control_setting);
        plainTextEdit_command_rx_2->setObjectName(QStringLiteral("plainTextEdit_command_rx_2"));
        plainTextEdit_command_rx_2->setGeometry(QRect(210, 90, 671, 61));
        layoutWidget_3 = new QWidget(groupBox_control_setting);
        layoutWidget_3->setObjectName(QStringLiteral("layoutWidget_3"));
        layoutWidget_3->setGeometry(QRect(10, 160, 491, 667));
        formLayout_12 = new QFormLayout(layoutWidget_3);
        formLayout_12->setObjectName(QStringLiteral("formLayout_12"));
        label_command_21 = new QLabel(layoutWidget_3);
        label_command_21->setObjectName(QStringLiteral("label_command_21"));
        sizePolicy.setHeightForWidth(label_command_21->sizePolicy().hasHeightForWidth());
        label_command_21->setSizePolicy(sizePolicy);
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_21->setPalette(palette2);
        label_command_21->setFont(font);
        label_command_21->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_21->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(0, QFormLayout::LabelRole, label_command_21);

        plainTextEdit_range_8 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_8->setObjectName(QStringLiteral("plainTextEdit_range_8"));

        formLayout_12->setWidget(0, QFormLayout::FieldRole, plainTextEdit_range_8);

        label_command_22 = new QLabel(layoutWidget_3);
        label_command_22->setObjectName(QStringLiteral("label_command_22"));
        sizePolicy.setHeightForWidth(label_command_22->sizePolicy().hasHeightForWidth());
        label_command_22->setSizePolicy(sizePolicy);
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_22->setPalette(palette3);
        label_command_22->setFont(font);
        label_command_22->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_22->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(1, QFormLayout::LabelRole, label_command_22);

        plainTextEdit_range_9 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_9->setObjectName(QStringLiteral("plainTextEdit_range_9"));

        formLayout_12->setWidget(1, QFormLayout::FieldRole, plainTextEdit_range_9);

        label_command_23 = new QLabel(layoutWidget_3);
        label_command_23->setObjectName(QStringLiteral("label_command_23"));
        sizePolicy.setHeightForWidth(label_command_23->sizePolicy().hasHeightForWidth());
        label_command_23->setSizePolicy(sizePolicy);
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush);
        palette4.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette4.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette4.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette4.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette4.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette4.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_23->setPalette(palette4);
        label_command_23->setFont(font);
        label_command_23->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_23->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(2, QFormLayout::LabelRole, label_command_23);

        plainTextEdit_range_10 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_10->setObjectName(QStringLiteral("plainTextEdit_range_10"));

        formLayout_12->setWidget(2, QFormLayout::FieldRole, plainTextEdit_range_10);

        label_command_24 = new QLabel(layoutWidget_3);
        label_command_24->setObjectName(QStringLiteral("label_command_24"));
        sizePolicy.setHeightForWidth(label_command_24->sizePolicy().hasHeightForWidth());
        label_command_24->setSizePolicy(sizePolicy);
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush);
        palette5.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette5.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette5.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette5.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_24->setPalette(palette5);
        label_command_24->setFont(font);
        label_command_24->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_24->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(3, QFormLayout::LabelRole, label_command_24);

        plainTextEdit_range_11 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_11->setObjectName(QStringLiteral("plainTextEdit_range_11"));

        formLayout_12->setWidget(3, QFormLayout::FieldRole, plainTextEdit_range_11);

        label_command_25 = new QLabel(layoutWidget_3);
        label_command_25->setObjectName(QStringLiteral("label_command_25"));
        sizePolicy.setHeightForWidth(label_command_25->sizePolicy().hasHeightForWidth());
        label_command_25->setSizePolicy(sizePolicy);
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette6.setBrush(QPalette::Active, QPalette::Text, brush);
        palette6.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette6.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette6.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette6.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette6.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_25->setPalette(palette6);
        label_command_25->setFont(font);
        label_command_25->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_25->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(4, QFormLayout::LabelRole, label_command_25);

        plainTextEdit_range_12 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_12->setObjectName(QStringLiteral("plainTextEdit_range_12"));

        formLayout_12->setWidget(4, QFormLayout::FieldRole, plainTextEdit_range_12);

        label_command_26 = new QLabel(layoutWidget_3);
        label_command_26->setObjectName(QStringLiteral("label_command_26"));
        sizePolicy.setHeightForWidth(label_command_26->sizePolicy().hasHeightForWidth());
        label_command_26->setSizePolicy(sizePolicy);
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette7.setBrush(QPalette::Active, QPalette::Text, brush);
        palette7.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette7.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette7.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette7.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette7.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_26->setPalette(palette7);
        label_command_26->setFont(font);
        label_command_26->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_26->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(5, QFormLayout::LabelRole, label_command_26);

        plainTextEdit_range_13 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_13->setObjectName(QStringLiteral("plainTextEdit_range_13"));

        formLayout_12->setWidget(5, QFormLayout::FieldRole, plainTextEdit_range_13);

        label_command_27 = new QLabel(layoutWidget_3);
        label_command_27->setObjectName(QStringLiteral("label_command_27"));
        sizePolicy.setHeightForWidth(label_command_27->sizePolicy().hasHeightForWidth());
        label_command_27->setSizePolicy(sizePolicy);
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette8.setBrush(QPalette::Active, QPalette::Text, brush);
        palette8.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette8.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette8.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette8.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette8.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette8.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_27->setPalette(palette8);
        label_command_27->setFont(font);
        label_command_27->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_27->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(6, QFormLayout::LabelRole, label_command_27);

        plainTextEdit_range_14 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_14->setObjectName(QStringLiteral("plainTextEdit_range_14"));

        formLayout_12->setWidget(6, QFormLayout::FieldRole, plainTextEdit_range_14);

        label_command_28 = new QLabel(layoutWidget_3);
        label_command_28->setObjectName(QStringLiteral("label_command_28"));
        sizePolicy.setHeightForWidth(label_command_28->sizePolicy().hasHeightForWidth());
        label_command_28->setSizePolicy(sizePolicy);
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette9.setBrush(QPalette::Active, QPalette::Text, brush);
        palette9.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette9.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette9.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette9.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette9.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette9.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_28->setPalette(palette9);
        label_command_28->setFont(font);
        label_command_28->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_28->setAlignment(Qt::AlignCenter);

        formLayout_12->setWidget(7, QFormLayout::LabelRole, label_command_28);

        plainTextEdit_range_15 = new QPlainTextEdit(layoutWidget_3);
        plainTextEdit_range_15->setObjectName(QStringLiteral("plainTextEdit_range_15"));

        formLayout_12->setWidget(7, QFormLayout::FieldRole, plainTextEdit_range_15);

        layoutWidget_4 = new QWidget(groupBox_control_setting);
        layoutWidget_4->setObjectName(QStringLiteral("layoutWidget_4"));
        layoutWidget_4->setGeometry(QRect(510, 160, 371, 458));
        formLayout_13 = new QFormLayout(layoutWidget_4);
        formLayout_13->setObjectName(QStringLiteral("formLayout_13"));
        label_command_29 = new QLabel(layoutWidget_4);
        label_command_29->setObjectName(QStringLiteral("label_command_29"));
        sizePolicy.setHeightForWidth(label_command_29->sizePolicy().hasHeightForWidth());
        label_command_29->setSizePolicy(sizePolicy);
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette10.setBrush(QPalette::Active, QPalette::Text, brush);
        palette10.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette10.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette10.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette10.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette10.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette10.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_29->setPalette(palette10);
        label_command_29->setFont(font);
        label_command_29->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_29->setAlignment(Qt::AlignCenter);

        formLayout_13->setWidget(0, QFormLayout::LabelRole, label_command_29);

        plainTextEdit_freq_7 = new QPlainTextEdit(layoutWidget_4);
        plainTextEdit_freq_7->setObjectName(QStringLiteral("plainTextEdit_freq_7"));

        formLayout_13->setWidget(0, QFormLayout::FieldRole, plainTextEdit_freq_7);

        label_command_30 = new QLabel(layoutWidget_4);
        label_command_30->setObjectName(QStringLiteral("label_command_30"));
        sizePolicy.setHeightForWidth(label_command_30->sizePolicy().hasHeightForWidth());
        label_command_30->setSizePolicy(sizePolicy);
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette11.setBrush(QPalette::Active, QPalette::Text, brush);
        palette11.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette11.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette11.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette11.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette11.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette11.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_30->setPalette(palette11);
        label_command_30->setFont(font);
        label_command_30->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_30->setAlignment(Qt::AlignCenter);

        formLayout_13->setWidget(1, QFormLayout::LabelRole, label_command_30);

        label_command_31 = new QLabel(layoutWidget_4);
        label_command_31->setObjectName(QStringLiteral("label_command_31"));
        sizePolicy.setHeightForWidth(label_command_31->sizePolicy().hasHeightForWidth());
        label_command_31->setSizePolicy(sizePolicy);
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette12.setBrush(QPalette::Active, QPalette::Text, brush);
        palette12.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette12.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette12.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette12.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette12.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette12.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette12.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette12.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_31->setPalette(palette12);
        label_command_31->setFont(font);
        label_command_31->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_31->setAlignment(Qt::AlignCenter);

        formLayout_13->setWidget(2, QFormLayout::LabelRole, label_command_31);

        label_command_32 = new QLabel(layoutWidget_4);
        label_command_32->setObjectName(QStringLiteral("label_command_32"));
        sizePolicy.setHeightForWidth(label_command_32->sizePolicy().hasHeightForWidth());
        label_command_32->setSizePolicy(sizePolicy);
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette13.setBrush(QPalette::Active, QPalette::Text, brush);
        palette13.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette13.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette13.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette13.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette13.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette13.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_32->setPalette(palette13);
        label_command_32->setFont(font);
        label_command_32->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_32->setAlignment(Qt::AlignCenter);

        formLayout_13->setWidget(3, QFormLayout::LabelRole, label_command_32);

        label_command_33 = new QLabel(layoutWidget_4);
        label_command_33->setObjectName(QStringLiteral("label_command_33"));
        sizePolicy.setHeightForWidth(label_command_33->sizePolicy().hasHeightForWidth());
        label_command_33->setSizePolicy(sizePolicy);
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette14.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette14.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette14.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette14.setBrush(QPalette::Active, QPalette::Text, brush);
        palette14.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette14.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette14.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette14.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette14.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette14.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette14.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette14.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_33->setPalette(palette14);
        label_command_33->setFont(font);
        label_command_33->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_33->setAlignment(Qt::AlignCenter);

        formLayout_13->setWidget(4, QFormLayout::LabelRole, label_command_33);

        label_command_34 = new QLabel(layoutWidget_4);
        label_command_34->setObjectName(QStringLiteral("label_command_34"));
        sizePolicy.setHeightForWidth(label_command_34->sizePolicy().hasHeightForWidth());
        label_command_34->setSizePolicy(sizePolicy);
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Light, brush2);
        palette15.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette15.setBrush(QPalette::Active, QPalette::Dark, brush2);
        palette15.setBrush(QPalette::Active, QPalette::Mid, brush2);
        palette15.setBrush(QPalette::Active, QPalette::Text, brush);
        palette15.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Active, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Active, QPalette::Shadow, brush2);
        palette15.setBrush(QPalette::Active, QPalette::AlternateBase, brush2);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipBase, brush3);
        palette15.setBrush(QPalette::Active, QPalette::ToolTipText, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Dark, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Mid, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Inactive, QPalette::Shadow, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush2);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush3);
        palette15.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Midlight, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Dark, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Mid, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Text, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::ButtonText, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette15.setBrush(QPalette::Disabled, QPalette::Shadow, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush2);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush3);
        palette15.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush2);
        label_command_34->setPalette(palette15);
        label_command_34->setFont(font);
        label_command_34->setStyleSheet(QStringLiteral("background-color: rgb(16, 32, 64);"));
        label_command_34->setAlignment(Qt::AlignCenter);

        formLayout_13->setWidget(5, QFormLayout::LabelRole, label_command_34);

        plainTextEdit_freq_8 = new QPlainTextEdit(layoutWidget_4);
        plainTextEdit_freq_8->setObjectName(QStringLiteral("plainTextEdit_freq_8"));

        formLayout_13->setWidget(1, QFormLayout::FieldRole, plainTextEdit_freq_8);

        plainTextEdit_freq_9 = new QPlainTextEdit(layoutWidget_4);
        plainTextEdit_freq_9->setObjectName(QStringLiteral("plainTextEdit_freq_9"));

        formLayout_13->setWidget(2, QFormLayout::FieldRole, plainTextEdit_freq_9);

        plainTextEdit_freq_10 = new QPlainTextEdit(layoutWidget_4);
        plainTextEdit_freq_10->setObjectName(QStringLiteral("plainTextEdit_freq_10"));

        formLayout_13->setWidget(3, QFormLayout::FieldRole, plainTextEdit_freq_10);

        plainTextEdit_freq_11 = new QPlainTextEdit(layoutWidget_4);
        plainTextEdit_freq_11->setObjectName(QStringLiteral("plainTextEdit_freq_11"));

        formLayout_13->setWidget(4, QFormLayout::FieldRole, plainTextEdit_freq_11);

        plainTextEdit_freq_12 = new QPlainTextEdit(layoutWidget_4);
        plainTextEdit_freq_12->setObjectName(QStringLiteral("plainTextEdit_freq_12"));

        formLayout_13->setWidget(5, QFormLayout::FieldRole, plainTextEdit_freq_12);

        pushButton_save = new QPushButton(groupBox_control_setting);
        pushButton_save->setObjectName(QStringLiteral("pushButton_save"));
        pushButton_save->setGeometry(QRect(520, 770, 121, 41));
        pushButton_2 = new QPushButton(groupBox_control_setting);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(660, 770, 121, 41));

        gridLayout->addWidget(groupBox_control_setting, 0, 0, 1, 1);


        retranslateUi(DialogCommandSet);

        QMetaObject::connectSlotsByName(DialogCommandSet);
    } // setupUi

    void retranslateUi(QDialog *DialogCommandSet)
    {
        DialogCommandSet->setWindowTitle(QApplication::translate("DialogCommandSet", "Dialog", Q_NULLPTR));
        groupBox_control_setting->setTitle(QString());
        label_command_3->setText(QApplication::translate("DialogCommandSet", "L\341\273\207nh ph\303\241t:", Q_NULLPTR));
        toolButton_set_command_2->setText(QApplication::translate("DialogCommandSet", "OK", Q_NULLPTR));
        label_command_20->setText(QApplication::translate("DialogCommandSet", "L\341\273\207nh t\341\272\257t ph\303\241t:", Q_NULLPTR));
        label_command_21->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 1.5nm:", Q_NULLPTR));
        label_command_22->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 3nm:", Q_NULLPTR));
        label_command_23->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 6nm:", Q_NULLPTR));
        label_command_24->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 12nm:", Q_NULLPTR));
        label_command_25->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 24nm:", Q_NULLPTR));
        label_command_26->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 48nm:", Q_NULLPTR));
        label_command_27->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 96nm:", Q_NULLPTR));
        label_command_28->setText(QApplication::translate("DialogCommandSet", "Thang c\341\273\261 ly 192nm:", Q_NULLPTR));
        label_command_29->setText(QApplication::translate("DialogCommandSet", "T\341\272\247n s\341\273\221 1:", Q_NULLPTR));
        label_command_30->setText(QApplication::translate("DialogCommandSet", "T\341\272\247n s\341\273\221 2:", Q_NULLPTR));
        label_command_31->setText(QApplication::translate("DialogCommandSet", "T\341\272\247n s\341\273\221 3:", Q_NULLPTR));
        label_command_32->setText(QApplication::translate("DialogCommandSet", "T\341\272\247n s\341\273\221 4:", Q_NULLPTR));
        label_command_33->setText(QApplication::translate("DialogCommandSet", "T\341\272\247n s\341\273\221 5:", Q_NULLPTR));
        label_command_34->setText(QApplication::translate("DialogCommandSet", "T\341\272\247n s\341\273\221 6:", Q_NULLPTR));
        pushButton_save->setText(QApplication::translate("DialogCommandSet", "L\306\260u", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("DialogCommandSet", "B\341\273\217", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class DialogCommandSet: public Ui_DialogCommandSet {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOGCOMMANDSET_H
