/********************************************************************************
** Form generated from reading UI file 'dialogdocumentation.ui'
**
** Created by: Qt User Interface Compiler version 5.7.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOGDOCUMENTATION_H
#define UI_DIALOGDOCUMENTATION_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDialogButtonBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_DialogDocumentation
{
public:
    QDialogButtonBox *buttonBox;
    QTabWidget *tabWidget;
    QWidget *tab;
    QTextBrowser *textBrowser;
    QWidget *tab_2;
    QTextBrowser *textBrowser_2;

    void setupUi(QDialog *DialogDocumentation)
    {
        if (DialogDocumentation->objectName().isEmpty())
            DialogDocumentation->setObjectName(QStringLiteral("DialogDocumentation"));
        DialogDocumentation->resize(832, 642);
        buttonBox = new QDialogButtonBox(DialogDocumentation);
        buttonBox->setObjectName(QStringLiteral("buttonBox"));
        buttonBox->setGeometry(QRect(450, 580, 341, 32));
        buttonBox->setOrientation(Qt::Horizontal);
        buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
        tabWidget = new QTabWidget(DialogDocumentation);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(30, 10, 781, 571));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        textBrowser = new QTextBrowser(tab);
        textBrowser->setObjectName(QStringLiteral("textBrowser"));
        textBrowser->setGeometry(QRect(10, 30, 731, 481));
        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        textBrowser_2 = new QTextBrowser(tab_2);
        textBrowser_2->setObjectName(QStringLiteral("textBrowser_2"));
        textBrowser_2->setGeometry(QRect(10, 20, 761, 521));
        tabWidget->addTab(tab_2, QString());

        retranslateUi(DialogDocumentation);
        QObject::connect(buttonBox, SIGNAL(accepted()), DialogDocumentation, SLOT(accept()));
        QObject::connect(buttonBox, SIGNAL(rejected()), DialogDocumentation, SLOT(reject()));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(DialogDocumentation);
    } // setupUi

    void retranslateUi(QDialog *DialogDocumentation)
    {
        DialogDocumentation->setWindowTitle(QApplication::translate("DialogDocumentation", "Dialog", Q_NULLPTR));
        textBrowser->setHtml(QApplication::translate("DialogDocumentation", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; font-weight:600; color:#222222; background-color:#ffffff;\">C\303\241ch \304\221\341\272\267t thang c\341\273\261 ly cho c\303\241c ch\341\272\277 \304\221\341\273\231 t\303\255n hi\341\273\207u kh\303\241c nhau \341\273\237 \303\264 \304\221\341\272\267t l\341\273\207nh:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'Arial,Helvetica,sans-seri"
                        "f'; font-size:8pt; color:#222222; background-color:#ffffff;\">s\341\273\255 d\341\273\245ng d\341\272\245u &quot;;&quot; \304\221\341\273\203 ng\304\203n c\303\241ch c\303\241c l\341\273\207nh.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222; background-color:#ffffff;\">s\341\273\255 d\341\273\245ng d\341\272\245u &quot;*&quot; \304\221\341\273\203 ng\304\203n c\303\241ch c\303\241c ch\341\272\277 \304\221\341\273\231</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222; background-color:#ffffff;\">v\303\255 d\341\273\245:\302\240</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0"
                        "px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222; background-color:#ffffff;\">n\341\272\277u \304\221\341\272\267t l\341\273\207nh thang c\341\273\261 ly 8 h\341\272\243i l\303\275 l\303\240 aaab1111;aaab1111*aaab2222;08ab2222*08ab3333</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222; background-color:#ffffff;\">th\303\254 khi ng\306\260\341\273\235i d\303\271ng nh\341\272\245n n\303\272t 8NM,\302\240</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222; background-color:#ffffff;\">n\341\272\277u \304\221ang \341\273\237"
                        " ch\341\272\277 \304\221\341\273\231 xung \304\221\306\241n l\341\273\207nh g\341\273\255i s\341\272\275 l\303\240\302\240 aaab1111;aaab1111\302\240\302\240</span><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222;\">n\341\272\277u \304\221ang \341\273\237 ch\341\272\277 \304\221\341\273\231 xung ph\341\273\251c t\341\272\241p l\341\273\207nh g\341\273\255i s\341\272\275 l\303\240\302\240\302\240 aaab2222;08ab2222\302\240</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222;\">n\341\272\277u \304\221ang \341\273\237 ch\341\272\277 \304\221\341\273\231 gi\341\272\243 li\303\252n t\341"
                        "\273\245c l\341\273\207nh g\341\273\255i s\341\272\275 l\303\240\302\240 \302\24008ab3333\302\240</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Arial,Helvetica,sans-serif'; font-size:8pt; color:#222222;\"><br /></p></body></html>", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("DialogDocumentation", "Basic", Q_NULLPTR));
        textBrowser_2->setHtml(QApplication::translate("DialogDocumentation", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<table border=\"1\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;\" width=\"688\" cellspacing=\"0\" cellpadding=\"0\">\n"
"<tr>\n"
"<td width=\"36\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width=\"57\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top"
                        ":12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0x0F</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width=\"57\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"4\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width"
                        "=\"53\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width=\"53\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width=\"187\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; "
                        "font-size:12pt;\">T\341\272\247n s\341\273\221 DDS ph\303\241t</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0x10</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left"
                        ":0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"4\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; p"
                        "adding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">T\341\272\247n s\341\273\221 DDS thu</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240<"
                        "/span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0x11</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"2\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><sp"
                        "an style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"2\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0p"
                        "x; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">Bi\303\252n \304\221\341\273\231 DDS phat/thu</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; paddin"
                        "g-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0x12</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width=\"61.75\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">1/0</span><span style=\" f"
                        "ont-size:8pt;\"> </span></p></td>\n"
"<td width=\"61.75\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width=\"61.75\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td width=\"61.75\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;"
                        "\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-b"
                        "lock-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">Sel rx_xung</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0x13</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-botto"
                        "m:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"2\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p><"
                        "/td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</s"
                        "pan><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt; font-weight:600;\">Cong_value</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0"
                        "; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0x14</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"2\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" mar"
                        "gin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; paddin"
                        "g-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt; font-weight:600;\">S\303\264 xung tr\341\273\221ng TR_RX</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif';"
                        " font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">21</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent"
                        ":0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">1/0</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; m"
                        "argin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padd"
                        "ing-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt; font-weight:600;\">chon_ma_M_ng_nhi\303\252n</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\""
                        ">22</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"2\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-"
                        "height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-"
                        "left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt; font-weight:600;\">Index test</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-"
                        "left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">23</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"2\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\""
                        ">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span "
                        "style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">gia_tri_han_bien</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-b"
                        "ottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">24</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; pa"
                        "dding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8p"
                        "t;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roma"
                        "n,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">T\341\272\257t_ph\303\241t_sof_nhanh/ch\341\273\215n xung ph\303\241t</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-t"
                        "op:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">25</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"2\" style=\" padding-l"
                        "eft:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</s"
                        "pan><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">Ena_phat_ko_\304\221x\341\273\251ng/data_ko_\304\221x\341\273\251ng</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0"
                        "px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">26</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<"
                        "p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
""
                        "<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\""
                        ">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">gia_tri_ch_hoa/ena_c\303\242n_b\304\203ng_t\341\272\241p</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:"
                        "0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">27</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-"
                        "bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </s"
                        "pan></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif';"
                        " font-size:12pt;\">Ch\341\273\215n baker suy bi\341\272\277n</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">28</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px"
                        "; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0;"
                        " padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;"
                        "\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">Ch\341\273\215n th ki\341\273\203m tra chipcore</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent"
                        ":0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">29</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; marg"
                        "in-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">x</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding"
                        "-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </sp"
                        "an></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">Dk kdtt</span><span style=\" font-size:8pt;\"> </span></p></td></tr>\n"
"<tr>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-fa"
                        "mily:'Times New Roman,serif'; font-size:12pt;\">0xAA</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">0xAB</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td colspan=\"4\" style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt"
                        "-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt;\">\302\240</span><span style=\" font-size:8pt;\"> </span></p></td>\n"
"<td style=\" padding-left:0; padding-right:0; padding-top:0; padding-bottom:0;\">\n"
"<p style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:125%;\"><span style=\" font-family:'Times New Roman,serif'; font-size:12pt; font-weight:600;\">\304\220K, tham s\341\273\221 Module</span><span style=\" font-size:8pt;\"> </span></p></td></tr></table></body></html>", Q_NULLPTR));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("DialogDocumentation", "Advanced", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class DialogDocumentation: public Ui_DialogDocumentation {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOGDOCUMENTATION_H
